image: docker:stable

variables:
    IMAGE_NAME: aspen-dev-box:main

services:
    - docker:19.03.12-dind

build_image:
    script:
        - docker build -t $CI_REGISTRY/aspen-discovery/aspen-dev-box-image/$IMAGE_NAME .
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker push $CI_REGISTRY/aspen-discovery/aspen-dev-box-image/$IMAGE_NAME
